### PR TITLE
#180 #179 #176 #155

### LINKED ISSUE #155: Hidden relations reappear after opening the OG again
I have created two tabs in Sbírka OG. In the fist tab are ONLY relations between terms from Sbírka. The second tab shall contain ONLY mapping to upper level vocabularies. This thing is, that most of the terms mapped are objects. I want to see here only objects, so automatically created relations between them were hidden. Unfortunately, if I get back to the WS and open the tab, relations are back.

### LINKED ISSUE #176: "Create new concept" window cannot be confirmed by enter
It looks like this was caused during the process of adding new label in english.

### LINKED ISSUE #179: Canvas is centered in a place without any graph
Tab číselníky in Sbírka looks empty, but it is just not centered at a place with any data.

### LINKED ISSUE #180: I cannot create term Část althought it does not yet exist
In Sbírka I am not allowed to create new term with label Část. I'm said that it already exist, but it does not (it does in another vocabulary).

### LINKED ISSUE #186: Almost all specializations of types have disappeared from canvas
In tab Číselník, almost all specializations (leaves on the outer rim) and the top level term (in the middle) have disappeared (i.e. went invisible). This cannot happen.

### PR DESCRIPTION
**Pull request by bindetad**
### Changes:
* Closes #180.
* Closes #179 - the canvas origin is reset on diagram switch.
* Closes #176.
* Closes #155.
* Added a `connections to` table to the `Connections` section of the detail panel, with its own `Expand connections` button. Since the hidden full connections won't reappear on reload when #155 is resolved, the user would have to remember that the connection exists in order to bring it back - hence the addition of `connections to` table after the `connections from` table.

#### Edit:
* Closes #186.
* #179 solution altered - [see comment below](https://github.com/opendata-mvcr/ontoGrapher/pull/184#issuecomment-743870235).

### Deploy previews:
* [JaKl Obchodní rejstřík](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance201242184)
* [V-SGoV pro číselníky](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-145753951)
* [GSGoV klasifikací a číselníků](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance2045554666)
* [Sbírka](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1178651091)
* [mm-test](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-2000996011)
* [Marie test](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-530560086)
* [Datové fondy VS](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1153182747)
* [ontoGrapher test](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1087289886)
* [ML test](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1101091271)
* [Karel TestX](https://deploy-preview-184--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1170301076)

### CODE REVIEW

**Comment by MichalMed** [comment]
z canvasu mi zmizela vazba na pojem číselník z V-SGoV

**Comment by bindetad** [comment]
In dea7ab1 with this PR, the following changes were made: #186 was (hopefully) resolved; I attached images in a [comment in the issue](https://github.com/opendata-mvcr/ontoGrapher/issues/186#issuecomment-743867972) so you can see it before you try it. The data is unaffected.

**Comment by MichalMed** [comment]
Yes, you can see hlava and číselník, because I have added it (it was difficult to work on that without seeing it :))
To the #179 : I agree this is much better, however I would prefer "return where you came from" solution as described in #179 . Anyway, close this, I'm adding new issue with "return where you came from solution", which can be performed later.

**Review by MichalMed — APPROVED** [review]

**Review by MichalMed — APPROVED** [review]
Everything Ok, except #179 additional features moved to new issue #188 .

**Comment by bindetad** [comment]
Since you are not a member of the @opendata-mvcr/c5-backend-reviewers codeowners group, I also need an approval from one of those members as well.

**Review by psiotwo — APPROVED** [review]
lgtm

**Pull request merged**
