### PR TITLE
[#187] Zoom function 

### LINKED ISSUE #187: Zoom In/Out support in a diagram.
It should be possible to Zoom In/Zoom Out in a diagram in OntoGrapher.

### PR DESCRIPTION
**Pull request by bindetad**
## Affected issues
* Closes #187.
## Detailed changes:
* (Un)Zoom functionality implemented.
* Use by scrolling/using the + - buttons on the menu bar.
* ~~Added "Reset zoom" & "Center view" buttons in the "View" submenu~~ The "Reset zoom" and "Center view" options are now buttons on the menu bar as of c27cf16.
## Deploy previews:
* [JaKl Obchodní rejstřík](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance201242184)
* [V-SGoV pro číselníky](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-145753951)
* [GSGoV klasifikací a číselníků](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance2045554666)
* [Sbírka](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1178651091)
* [mm-test](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-2000996011)
* [Marie test](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-530560086)
* [Datové fondy VS](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1153182747)
* [ontoGrapher test](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1087289886)
* [ML test](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance-1101091271)
* [Karel TestX](https://deploy-preview-192--ontographer.netlify.app/?workspace=https://slovník.gov.cz/datový/pracovní-prostor/pojem/metadatový-kontext/instance1170301076)

### CODE REVIEW

**Review by psiotwo — COMMENTED** [review]
see my comment already posted.

**Comment by bindetad** [comment]
In c27cf16, I altered the UI - changed the icons and moved the functions from the View submenu - what do you think? I have also altered the centering, but I wasn't able to replicate the scrolling issue - what do you mean when you say the page is scrolling as well?

**Comment by psiotwo** [comment]
> In [c27cf16](https://github.com/opendata-mvcr/ontoGrapher/commit/c27cf1654902ceab82eec979410062a5166b8308), I altered the UI - changed the icons and moved the functions from the View submenu - what do you think? I have also altered the centering, but I wasn't able to replicate the scrolling issue - what do you mean when you say the page is scrolling as well?

The buttons seems much more understandable now IMO.

In this version the scrolling works OK for me for some time. But Zooming out using the mouse makes the whole diagram disappear. After I Zoom in using the mouse, I am not able to Zoom In/Out any more and I am getting the errors as attached 
image

**Comment by bindetad** [comment]
In 11cda26, zooming is limited to 10 - 200% and the math has been rounded - I can't reproduce the bug anymore.

**Review by psiotwo — APPROVED** [review]
lgtm

**Comment by MichalMed** [comment]
lgtm

**Pull request merged**
